/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quan_ly_quan_bida;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Qly_Ban extends javax.swing.JFrame {
    private String selectedTable = "";
    private LocalTime startTime;
    private LocalTime endTime;

    /**
     * Creates new form Qly_Ban
     */
    public Qly_Ban() {
        initComponents();
        updateDateTime();
    }
    private void updateDateTime() {
        new Thread(() -> {
            while (true) {
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date date = new Date();
                lbngay.setText("Ngày: " + formatter.format(date));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnban2 = new keeptoo.KButton();
        btnban3 = new keeptoo.KButton();
        btnban4 = new keeptoo.KButton();
        btnban1 = new keeptoo.KButton();
        btnban6 = new keeptoo.KButton();
        btnban7 = new keeptoo.KButton();
        btnban8 = new keeptoo.KButton();
        btnban5 = new keeptoo.KButton();
        btnketthuc = new keeptoo.KButton();
        btntinhgio = new keeptoo.KButton();
        btnbatdau = new keeptoo.KButton();
        lbsogiochoi = new javax.swing.JLabel();
        lbtongtien = new javax.swing.JLabel();
        lbngay = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnban2.setText("Bàn 2");
        btnban2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnban2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban2ActionPerformed(evt);
            }
        });

        btnban3.setText("Bàn 3");
        btnban3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnban3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban3ActionPerformed(evt);
            }
        });

        btnban4.setText("Bàn 4");
        btnban4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnban4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban4ActionPerformed(evt);
            }
        });

        btnban1.setText("Bàn 1");
        btnban1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnban1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban1ActionPerformed(evt);
            }
        });

        btnban6.setText("Bàn 6");
        btnban6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnban6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban6ActionPerformed(evt);
            }
        });

        btnban7.setText("Bàn 7");
        btnban7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnban7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban7ActionPerformed(evt);
            }
        });

        btnban8.setText("Bàn 8");
        btnban8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnban8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban8ActionPerformed(evt);
            }
        });

        btnban5.setText("Bàn 5");
        btnban5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnban5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban5ActionPerformed(evt);
            }
        });

        btnketthuc.setText("Kết Thúc");
        btnketthuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketthucActionPerformed(evt);
            }
        });

        btntinhgio.setText("Tính Giờ");
        btntinhgio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btntinhgio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntinhgioActionPerformed(evt);
            }
        });

        btnbatdau.setText("Bắt Đầu");
        btnbatdau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbatdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatdauActionPerformed(evt);
            }
        });

        lbsogiochoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbsogiochoi.setText("Số giờ chơi: ");

        lbtongtien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbtongtien.setText("Tổng Tiền: ");

        lbngay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbngay.setText("Ngày: ");

        txt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnban1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnban2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnban3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnban4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnban5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnban6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnban7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnban8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btntinhgio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbtongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(lbsogiochoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(239, 239, 239)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnban2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnban3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnban4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnban1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnban6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnban7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnban8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnban5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt1)
                    .addComponent(btnbatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btntinhgio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbngay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lbsogiochoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtongtien)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnban1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban1ActionPerformed
        // TODO add your handling code here:
        resetFieldsIfConditionsMet();
        selectedTable = "Ban1";
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime != null) {
            txt1.setText(startTime.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã chọn bàn 1");
    }//GEN-LAST:event_btnban1ActionPerformed

    private void btnban2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban2ActionPerformed
        // TODO add your handling code here:
        resetFieldsIfConditionsMet();
        selectedTable = "Ban2";
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime != null) {
            txt1.setText(startTime.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã chọn bàn 2");
    }//GEN-LAST:event_btnban2ActionPerformed

    private void btnban3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban3ActionPerformed
        // TODO add your handling code here:
        resetFieldsIfConditionsMet();
        selectedTable = "Ban3";
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime != null) {
            txt1.setText(startTime.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã chọn bàn 3");
    }//GEN-LAST:event_btnban3ActionPerformed

    private void btnban4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban4ActionPerformed
        // TODO add your handling code here:
       resetFieldsIfConditionsMet();
        selectedTable = "Ban4";
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime != null) {
            txt1.setText(startTime.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã chọn bàn 4");
    }//GEN-LAST:event_btnban4ActionPerformed

    private void btnban5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban5ActionPerformed
        // TODO add your handling code here:
        resetFieldsIfConditionsMet();
        selectedTable = "Ban5";
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime != null) {
            txt1.setText(startTime.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã chọn bàn 5");
    }//GEN-LAST:event_btnban5ActionPerformed

    private void btnban6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban6ActionPerformed
        // TODO add your handling code here:
        resetFieldsIfConditionsMet();
        selectedTable = "Ban6";
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime != null) {
            txt1.setText(startTime.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã chọn bàn 6");
    }//GEN-LAST:event_btnban6ActionPerformed

    private void btnban7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban7ActionPerformed
        // TODO add your handling code here:
        resetFieldsIfConditionsMet();
        selectedTable = "Ban7";
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime != null) {
            txt1.setText(startTime.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã chọn bàn 7");
    }//GEN-LAST:event_btnban7ActionPerformed

    private void btnban8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban8ActionPerformed
        // TODO add your handling code here:
        resetFieldsIfConditionsMet();
        selectedTable = "Ban8";
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime != null) {
            txt1.setText(startTime.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã chọn bàn 8");
    }//GEN-LAST:event_btnban8ActionPerformed

    private void resetFieldsIfConditionsMet() {
        if (!selectedTable.isEmpty() && startTime != null && endTime != null) {
            txt1.setText("");
            txt2.setText("");
        }
    }
    private void btnbatdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatdauActionPerformed
        // TODO add your handling code here:
        if (selectedTable.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn trước khi bắt đầu.");
            return;
        }
        startTime = getStartTimeFromDatabase(selectedTable);
        if (startTime == null) {
            startTime = LocalTime.now().withNano(0);
            saveStartTimeToDatabase(selectedTable, startTime);
        }
        txt1.setText(startTime.toString());
    }//GEN-LAST:event_btnbatdauActionPerformed

    private void btnketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketthucActionPerformed
        // TODO add your handling code here:
        if (startTime == null) {
            JOptionPane.showMessageDialog(this, "Chưa có giờ bắt đầu cho bàn đã chọn.");
            return;
        }
        endTime = LocalTime.now().withNano(0);
        txt2.setText(endTime.toString());
        saveEndTimeToDatabase(selectedTable, endTime);
    }//GEN-LAST:event_btnketthucActionPerformed

    private void btntinhgioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntinhgioActionPerformed
        // TODO add your handling code here:
        if (startTime == null || endTime == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng bắt đầu và kết thúc trước khi tính giờ.");
            return;
        }
        Duration duration = Duration.between(startTime, endTime);
        long totalSeconds = duration.getSeconds();
        long hours = totalSeconds / 3600;
        long minutes = (totalSeconds % 3600) / 60;
        long seconds = totalSeconds % 60;

        double totalAmount = (totalSeconds / 3600.0) * 50000;

        lbsogiochoi.setText(String.format("Số giờ chơi: %02d:%02d:%02d", hours, minutes, seconds));
        lbtongtien.setText(String.format("Tổng Tiền: %.2f VND", totalAmount));
        saveTotalAmountToDatabase(selectedTable, (long) totalAmount);
    }//GEN-LAST:event_btntinhgioActionPerformed

    private void saveStartTimeToDatabase(String tableName, LocalTime startTime) {
        String sql = "INSERT INTO " + tableName + " (ngay, gio_bat_dau) VALUES (?, ?)";
        try (Connection conn = Class_ket_noi.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, lbngay.getText().replace("Ngày: ", "").split(" ")[0]);
            ps.setString(2, startTime.toString());
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private LocalTime getStartTimeFromDatabase(String tableName) {
        String sql = "SELECT gio_bat_dau FROM " + tableName + " WHERE id = (SELECT MAX(id) FROM " + tableName + ") AND gio_ket_thuc IS NULL";
        try (Connection conn = Class_ket_noi.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return LocalTime.parse(rs.getString("gio_bat_dau"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    private void saveEndTimeToDatabase(String tableName, LocalTime endTime) {
        String sql = "UPDATE " + tableName + " SET gio_ket_thuc = ? WHERE id = (SELECT MAX(id) FROM " + tableName + ")";
        try (Connection conn = Class_ket_noi.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, endTime.toString());
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void saveTotalAmountToDatabase(String tableName, long totalAmount) {
        String sql = "UPDATE " + tableName + " SET tong_tien = ? WHERE id = (SELECT MAX(id) FROM " + tableName + ")";
        try (Connection conn = Class_ket_noi.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setLong(1, totalAmount);
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Qly_Ban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Qly_Ban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Qly_Ban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qly_Ban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Qly_Ban().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnban1;
    private keeptoo.KButton btnban2;
    private keeptoo.KButton btnban3;
    private keeptoo.KButton btnban4;
    private keeptoo.KButton btnban5;
    private keeptoo.KButton btnban6;
    private keeptoo.KButton btnban7;
    private keeptoo.KButton btnban8;
    private keeptoo.KButton btnbatdau;
    private keeptoo.KButton btnketthuc;
    private keeptoo.KButton btntinhgio;
    private javax.swing.JLabel lbngay;
    private javax.swing.JLabel lbsogiochoi;
    private javax.swing.JLabel lbtongtien;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
